server:
  port: 8021
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=medical
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      data-location: classpath:init/schema.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"